### ISSUE TITLE
Add code styles and standards to the project 

### ISSUE THREAD

**Issue by idanilt** [scalecube/scalecube-js#16]
Requirements
- Create editors file for IDEs
- Write styles & standards and enforce it on the CI (eslint, jslint or anything else)
- prettier? do we want it?

**Comment by idanilt** [comment]
#23

**Comment by dmitriyslaym** [comment]
### Linting (TSLint)
**tslint** is used in each package and has to be a devDependency there.
These scripts have to be added in each package to set up linting
`    "lint": "tslint '{src,tests}/**/*.{ts,tsx}'",`
`    "lint:fix": "yarn lint --fix",`
The configuration for the linting exists in the root (**tslint.json**).
**tslint:recommended** has been taken as base rules (a few rules have been disabled from it) and **tslint-config-prettier** is used in order to disable code-formatting rules (**Prettier** will take care of them). **tslint-config-prettier** always has to be the latest item **"extends"** array.

### Code formatting (Prettier and Remark)
**prettier** and **remark** packages are installed in the root of the project.
**Prettier** configuration exists in the root (**.prettierrc.js**).
These is a **precommit hook** for prettier, that will automatically run prettier before each commit for the files, that were changed within the commit.
**Remark** is used only to format **.md** files.
These scripts have to added in each package:
`"prettier": "prettier --write '{src,tests}/**/*.{ts,tsx}'"`
`"format": "yarn run lint:fix && yarn run prettier"`

### Root scripts
`"lint": "yarn lint-md && lerna run lint"` // used in CI/CD to validate the correct linting
`"format": "lerna run format"` // can be used to run **prettier** for the whole project and fix all the linting rules, that can be fixed automatically
