### ISSUE TITLE
Microservice on threads - RFC

### ISSUE THREAD

**Issue by IdoJS** [scalecube/scalecube-js#89]
## Proposition

in our current implementation, we are using global/window to keep our cluster of discoveries.
but we can't access window from a child thread.
therefor, we can't access the other discoveries from the  child thread.

so instead of creating a namespace on the global scope, we need to find a solution for sharing the data between the main thread and child threads.

### Possible solutions:
- using a sharedWorker.
- creating HOF connect that manage the microservice connection between the main thread and worker/iframe/... tread (and vica versa).

### Goals/Values

1. run microservice example in webworker.
2. run microservice example in node.

**Comment by dmitriyslaym** [comment]
As I understand, sharedWorker api is something specific only for browser environment. What about using Custom Events to change the data in clusters and postMessage to notify a worker or process (if we're talking about nodeJS) about the change in clusters?

**Comment by dmitriyslaym** [comment]
Should we cover the case, when there will be a worker inside a worker?

**Comment by IdoJS** [comment]
the case we want to cover is:
if we creating a microservice in a worker then on the creation the microservice use discovery.
in the current implementation, discovery is on the window/global, so when the discovery will try to get the cluster it will fail

**Comment by IdoJS** [comment]
since shared workers are not supported atm in safari we need to find another solution,
another possible solution is an "event-bus" which use MessageChannel:
**microservice will export:** 
createMicroservice, createMicroserviceWorker, MicroserviceWorker, transportChannel.

- createMicroservice({service: Service[], seedAddress: string, transportChannel : MessageChannel}):Microservice

- createMicroserviceWorker({workerPath:string , transportChannel : MessageChannel}):Microservice

- MicroserviceWorker({service: Service[], seedAddress: string}):void

- transportChannel : new MessageChannel();

- ASYNC_MODEL_TYPES : { REQUEST_STREAM, REQUEST_RESPONSE }

that way we are able to use the transportChannel to pass event between main thread and/or worker.

**Comment by idanilt** [comment]
As I see it it's not part of SC
Create 3 method instead of 1 is just overhead

The path should be:
- Provision your service (on worker, Iframe, main, nodejs, nodejs worker, or anywhere)
- Use the appropriate transport/s and discovery
- Making sure MS instances accessible to one another is part of delivering/bootstrap the system. we can't provide a magic solution for anyone

In order to run in web worker
- Provision service in web worker (or web workers, you can also put services inside main worker)
- Use RSocket (events provider)
- Discovery will also needs to support multi thread
- *Relay all events from each worker to all worker and main thread, and from main thread to all worker

*This part can be stand alone utility that we can offer but not part of SC core
